routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/lang/{locale}', function ($locale) {
    session()->put('locale', $locale);

    return redirect()->back();
});

Auth::routes(['verify' => true]);
Route::get('/admin/login', [App\Http\Controllers\Auth\LoginController::class, 'showAdminLoginForm']);
Route::post('/admin/login', [App\Http\Controllers\Auth\LoginController::class, 'adminLogin']);

Route::middleware('auth:admin')->group(function () {
    Route::get('/admin', [App\Http\Controllers\Admin\DashboardController::class, 'index']);
});

Route::get('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);
Route::get('/', [App\Http\Controllers\User\DashboardController::class, 'index'])->name('home');

Route::resource('home', App\Http\Controllers\HomeController::class);
Route::get('/home/{plan_id}/{id}', [App\Http\Controllers\HomeController::class, 'showCurrencyWise'])->name('showCurrencyWise');

Route::resource('dashboard', App\Http\Controllers\User\DashboardController::class);
Route::resource('server_monitor', App\Http\Controllers\User\MonitorServerController::class);
Route::resource('dns_server_monitor', App\Http\Controllers\DnsMonitoringController::class);
Route::resource('keyword_monitor', App\Http\Controllers\KeywordMonitoringController::class);
Route::resource('webpage_monitor', App\Http\Controllers\User\MonitorWebpageController::class);
Route::resource('api_monitor', App\Http\Controllers\User\MonitorApiController::class);
Route::resource('website_monitor', App\Http\Controllers\User\MonitorWebsiteController::class);
Route::resource('available_plans', App\Http\Controllers\User\AddPlanController::class);
Route::resource('server_incident', App\Http\Controllers\User\ServerIncidentController::class);
Route::resource('webpage_incident', App\Http\Controllers\User\WebpageIncidentController::class);
Route::resource('website_incident', App\Http\Controllers\User\WebsiteIncidentController::class);
Route::resource('status_page', App\Http\Controllers\User\StatusPageController::class);
Route::resource('api_incident', App\Http\Controllers\User\ApiIncidentController::class);
Route::resource('ssl_monitor', App\Http\Controllers\User\SslMonitorController::class);
Route::resource('domain_monitor', App\Http\Controllers\User\DomainMonitorController::class);

Route::resource('alert_manager', App\Http\Controllers\User\AlertManagerController::class);

Route::get('/server_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorServerController::class, 'bulk_create'])->name('server_bulk_create');
Route::post('/server_monitor/bulk_create', [App\Http\Controllers\User\MonitorServerController::class, 'bulk_store'])->name('server_bulk_store');
Route::get('/webpage_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorWebpageController::class, 'bulk_create'])->name('webpage_bulk_create');
Route::post('/webpage_monitor/bulk_create', [App\Http\Controllers\User\MonitorWebpageController::class, 'bulk_store'])->name('webpage_bulk_store');
Route::get('/api_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorApiController::class, 'bulk_create'])->name('api_bulk_create');
Route::post('/api_monitor/bulk_create', [App\Http\Controllers\User\MonitorApiController::class, 'bulk_store'])->name('api_bulk_store');
Route::get('/website_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorWebsiteController::class, 'bulk_create'])->name('website_bulk_create');
Route::post('/website_monitor/bulk_create', [App\Http\Controllers\User\MonitorWebsiteController::class, 'bulk_store'])->name('website_bulk_store');
Route::get('/ssl_monitor/bulk_create/add', [App\Http\Controllers\User\SslMonitorController::class, 'bulk_create'])->name('ssl_bulk_create');
Route::post('/ssl_monitor/bulk_create', [App\Http\Controllers\User\SslMonitorController::class, 'bulk_store'])->name('ssl_bulk_store');
Route::get('/domain_monitor/bulk_create/add', [App\Http\Controllers\User\DomainMonitorController::class, 'bulk_create'])->name('domain_bulk_create');
Route::post('/domain_monitor/bulk_create', [App\Http\Controllers\User\DomainMonitorController::class, 'bulk_store'])->name('domain_bulk_store');

Route::POST('/update_server_details/{uuid}', [App\Http\Controllers\User\ServerIncidentController::class, 'updateIncidentDetails'])->name('updateServerDetails');
Route::POST('/update_page_details/{uuid}', [App\Http\Controllers\User\WebpageIncidentController::class, 'updateIncidentDetails'])->name('updateWebpageDetails');
Route::POST('/update_api_details/{uuid}', [App\Http\Controllers\User\ApiIncidentController::class, 'updateIncidentDetails'])->name('updateApiDetails');
Route::delete('/delete_server_details/{uuid}', [App\Http\Controllers\User\ServerIncidentController::class, 'deleteDetails'])->name('deleteServerDetails');
Route::delete('/delete_page_details/{uuid}', [App\Http\Controllers\User\WebpageIncidentController::class, 'deleteDetails'])->name('deleteWebpageDetails');
Route::delete('/delete_api_details/{uuid}', [App\Http\Controllers\User\ApiIncidentController::class, 'deleteDetails'])->name('deleteApiDetails');

Route::post('/{id}/place_order', [App\Http\Controllers\User\AddPlanController::class, 'placeOrder'])->name('place_order');
Route::get('/profile', [App\Http\Controllers\User\ProfileController::class, 'index'])->name('userProfile');
Route::post('/profile/update', [App\Http\Controllers\User\ProfileController::class, 'update'])->name('userProfileUpdate');

Route::get('/public_page/{name}', [App\Http\Controllers\PublicPageController::class, 'monitorPublicPage'])->name('monitorPublicPage');

Route::get('status_pages/{name}', [App\Http\Controllers\ShowStatusPageController::class, 'showStatusPage'])->name('showStatusPage');

Route::resource('/admin/plans', App\Http\Controllers\Admin\PlanController::class);
Route::resource('/admin/users', App\Http\Controllers\Admin\UserController::class);
Route::resource('/admin/orders', App\Http\Controllers\Admin\OrderController::class);
Route::resource('/admin/services', App\Http\Controllers\Admin\ServiceController::class);
Route::resource('/admin/invoices', App\Http\Controllers\Admin\InvoiceController::class);
Route::resource('/admin/language', App\Http\Controllers\Admin\LanguageController::class);
Route::resource('/admin/interval', App\Http\Controllers\Admin\IntervalController::class);
Route::resource('/admin/addon', App\Http\Controllers\Admin\AddonController::class);
Route::resource('/admin/billing_address', App\Http\Controllers\Admin\AddressController::class);
Route::get('/admin/profile', [App\Http\Controllers\Admin\ProfileController::class, 'index'])->name('adminProfile');
Route::post('/admin/profile/update', [App\Http\Controllers\Admin\ProfileController::class, 'update'])->name('adminProfileUpdate');
Route::resource('/admin/gateways', App\Http\Controllers\Admin\GatewayDetailsController::class);
Route::resource('/admin/pricing', App\Http\Controllers\Admin\PricingController::class);
Route::resource('/admin/currency', App\Http\Controllers\Admin\CurrencyController::class);
Route::resource('/admin/settings', App\Http\Controllers\Admin\SettingController::class);
Route::resource('email_template', App\Http\Controllers\Admin\EmailTemplateController::class);

Route::get('/pricing/{id}/pricing_index', [App\Http\Controllers\Admin\PricingController::class, 'pricing_index'])->name('pricing_index');
Route::get('/pricing/{id}/pricing_create', [App\Http\Controllers\Admin\PricingController::class, 'pricing_create'])->name('pricing_create');
Route::get('/pricing/{plan_id}/pricing_edit/{id}', [App\Http\Controllers\Admin\PricingController::class, 'pricing_edit'])->name('pricing_edit');

Route::get('available_plans/invoice/{id}', [App\Http\Controllers\User\AddPlanController::class, 'invoice'])->name('invoice');
Route::get('/plan_details/{plan_id}/{id}', [App\Http\Controllers\User\HomeController::class, 'showCurrencyWise'])->name('showCurrencyWise');

Route::post('{id}/process_order', [App\Http\Controllers\GatewayController::class, 'processOrder'])->name('processOrder');
Route::get('success', [App\Http\Controllers\GatewayController::class, 'success'])->name('success');
Route::get('cancel', [App\Http\Controllers\GatewayController::class, 'cancel'])->name('cancel');

Route::post('{id}/stripe-payment-confirm', [App\Http\Controllers\GatewayController::class, 'stripePayment'])->name('stripe.payment');
Route::post('paypal_response', [App\Http\Controllers\GatewayController::class, 'paypalResponse'])->name('paypalResponse');

Route::post('{id}/mollie-payment', [App\Http\Controllers\GatewayController::class, 'molliePayment'])->name('mollie.payment');
Route::post('{id}/bank-transfer', [App\Http\Controllers\GatewayController::class, 'bankTransfer'])->name('bank_transfer');
Route::post('WebhookNotification', [App\Http\Controllers\GatewayController::class, 'handleMollieWebhookNotification'])->name('webhooks.mollie');

Route::get('{uuid}/refund', [App\Http\Controllers\Admin\RefundController::class, 'refund'])->name('refund');
Route::get('paypalRefund', [App\Http\Controllers\Admin\RefundController::class, 'paypalRefund'])->name('paypalRefund');

Route::post('{id}/paypal_payment', [App\Http\Controllers\GatewayController::class, 'payPalPayment'])->name('paypal.payment');
Route::get('/paypal_done', [App\Http\Controllers\GatewayController::class, 'payPalResponse'])->name('getDone');

Route::get('/get_servers_api', [App\Http\Controllers\User\StatusPageController::class, 'getServersApi'])->name('getServersApi');
Route::get('/get_webpages_api', [App\Http\Controllers\User\StatusPageController::class, 'getWebpagesApi'])->name('getWebpagesApi');

app/Models/StatusPage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StatusPage extends Model
{
    protected $primaryKey = 'uuid';

    public $incrementing = false;

    use HasFactory;

    protected $fillable = [
        'name', 'user_id', 'sub_domain', 'logo', 'description', 'slug',
    ];

    public function users(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

resources/views/status_page/create.blade.php
@extends('layouts.new_theme')

@section('content')

<div class="section-header">
    <h1>{{ __('Status Pages') }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard.index') }}">{{ __('Dashboard') }}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('status_page.index') }}">{{ __('Status Pages') }}</a>
        </div>
        <div class="breadcrumb-item">{{ __('Add Status Page') }}</div>
    </div>
</div>

<div class="section-body">

    <div class="row">
        <div class="col-12">
            @include('common.demo')
            @include('common.errors')
            <div class="card">
                <div class="card-header">
                    <h4>{{ __('Add Status Page') }}</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('status_page.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Name') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                    name="name" value="{{ old('name') }}" autocomplete="name" autofocus>

                                @error('name')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-capitalize">{{ __('Description') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea class="form-control @error('description') is-invalid @enderror"
                                    id="description" rows="5" name="description">{{ old('description') }} </textarea>
                                @error('description')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        @if ($enableSubdomain)
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-capitalize">{{ __('Sub domain') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="sub_domain" type="text"
                                    class="form-control @error('sub_domain') is-invalid @enderror" name="sub_domain"
                                    value="{{ old('sub_domain') }}" autocomplete="sub_domain" autofocus>

                                @error('sub_domain')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Enter your statuspage subdomain') }}.
                                    <br>
                                    {{ __('Eg: status.mydomain.com') }}.
                                </small>
                            </div>

                        </div>
                        @endif


                        <div class="form-group row mb-4" id="servers">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Servers') }}:</label>
                            <div class="col-sm-12 col-md-7" v-if="servers">
                                <input type="hidden" ref="server_ref" id="server_ref_id" value="" name="server_ids" />
                                <select-servers multiple :options="servers" taggable push-servers
                                    v-model="selected_servers" :reduce="servers => servers.uuid" label="name"
                                    @input="chooseMe">
                                </select-servers>
                            </div>
                        </div>

                        <div class="form-group row mb-4" id="webpages">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Webpages') }}:</label>
                            <div class="col-sm-12 col-md-7" v-if="webpages">
                                <input type="hidden" ref="webpage_ref" id="webpage_ref_id" value=""
                                    name="webpage_ids" />
                                <select-webpages multiple :options="webpages" taggable push-webpages
                                    v-model="selected_webpages" :reduce="webpages => webpages.uuid" label="name"
                                    @input="chooseMe">
                                </select-webpages>
                            </div>
                        </div>

                        <div class="form-group row mb-4" id="apis">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Apis') }}:</label>
                            <div class="col-sm-12 col-md-7" v-if="apis">
                                <input type="hidden" ref="api_ref" id="api_ref_id" value="" name="api_ids" />
                                <select-apis multiple :options="apis" taggable push-apis v-model="selected_apis"
                                    :reduce="apis => apis.uuid" label="name" @input="chooseMe">
                                </select-apis>
                            </div>
                        </div>

                        @if ($enableSubdomain)
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-capitalize">{{ __('Logo') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="logo" name="logo" type="file" class="form-control file"
                                    data-show-caption="true" value="{{ __($logo) }}" autocomplete="value" autofocus>
                                @error('logo')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        @endif

                        @if (config('app.env') != 'demo')
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-custom">{{ __('Add') }}</button>
                            </div>
                        </div>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var uuid = null;
    var current_servers = null;
    var current_webpages = null;
    var current_apis = null;
</script>
<script src="{{ asset('js/servers.js') }}"></script>
<script src="{{ asset('js/webpages.js') }}"></script>
<script src="{{ asset('js/apis.js') }}"></script>
@endsection

resources/views/status_page/edit.blade.php
@extends('layouts.new_theme')

@section('content')

<div class="section-header">
    <h1>{{ __('Status Pages') }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard.index') }}">{{ __('Dashboard') }}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('status_page.index') }}">{{ __('Status Pages') }}</a>
        </div>
        <div class="breadcrumb-item">{{ __('Edit Status Page') }}</div>
    </div>
</div>

<div class="section-body">

    <div class="row">
        <div class="col-12">
            @include('common.demo')
            @include('common.errors')
            <div class="card">
                <div class="card-header">
                    <h4>{{ __('Edit Status Page') }}</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('status_page.update', $uuid) }}" enctype="multipart/form-data">
                        @csrf

                        @method('PUT')

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Name') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                    name="name" value="{{ old('name', $name) }}" autocomplete="name" autofocus>

                                @error('name')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-capitalize">{{ __('Description') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <textarea class="form-control @error('description') is-invalid @enderror"
                                    id="description" rows="5"
                                    name="description">{{ old('description', $description) }} </textarea>
                                @error('description')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        @if ($enableSubdomain)
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-capitalize">{{ __('Sub domain') }}:*</label>
                                <div class="col-sm-12 col-md-7">
                                <input id="sub_domain" type="text"
                                    class="form-control @error('sub_domain') is-invalid @enderror" name="sub_domain"
                                    value="{{ old('sub_domain', $sub_domain) }}"
                                    autocomplete="sub_domain" autofocus>

                                @error('sub_domain')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Enter your statuspage subdomain') }}.
                                    <br>
                                    {{ __('Eg: status.mydomain.com') }}.
                                </small>
                            </div>

                        </div>
                        @endif

                        <div class="form-group row mb-4" id="servers">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Servers') }}:</label>
                            <div class="col-sm-12 col-md-7" v-if="servers">
                                <input type="hidden" ref="server_ref" id="server_ref_id" value="" name="server_ids" />
                                <select-servers multiple :options="servers" taggable push-servers
                                    v-model="selected_servers" :reduce="servers => servers.uuid" label="name"
                                    @input="chooseMe">
                                </select-servers>
                            </div>
                        </div>

                        <div class="form-group row mb-4" id="webpages">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Webpages') }}:</label>
                            <div class="col-sm-12 col-md-7" v-if="webpages">
                                <input type="hidden" ref="webpage_ref" id="webpage_ref_id" value=""
                                    name="webpage_ids" />
                                <select-webpages multiple :options="webpages" taggable push-webpages
                                    v-model="selected_webpages" :reduce="webpages => webpages.uuid" label="name"
                                    @input="chooseMe">
                                </select-webpages>
                            </div>
                        </div>

                        <div class="form-group row mb-4" id="apis">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Apis') }}:</label>
                            <div class="col-sm-12 col-md-7" v-if="apis">
                                <input type="hidden" ref="api_ref" id="api_ref_id" value="" name="api_ids" />
                                <select-apis multiple :options="apis" taggable push-apis v-model="selected_apis"
                                    :reduce="apis => apis.uuid" label="name" @input="chooseMe">
                                </select-apis>
                            </div>
                        </div>

                        @if ($enableSubdomain)
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3 text-capitalize">{{ __('Logo') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="logo" name="logo" type="file" class="form-control file"
                                    data-show-caption="true" value="{{ __($logo) }}" autocomplete="logo" autofocus>
                                @error('logo')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        @endif

                        @if (config('app.env') != 'demo')
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-custom">{{ __('Update') }}</button>
                            </div>
                        </div>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var uuid = '<?php echo $uuid; ?>';
    var current_servers = '@json($selected_servers)';
    var current_webpages = '@json($selected_webpages)';
    var current_apis = '@json($selected_apis)';
</script>
<script src="{{ asset('js/servers.js') }}"></script>
<script src="{{ asset('js/webpages.js') }}"></script>
<script src="{{ asset('js/apis.js') }}"></script>
@endsection

resources/views/status_page/index.blade.php
@extends('layouts.new_theme')

@section('content')

<div class="section-header">
    <h1>{{ __('Status Pages') }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard.index') }}">{{ __('Dashboard') }}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('plans.index') }}">{{ __('Status Pages') }}</a>
        </div>
        <div class="breadcrumb-item">{{ __('List of Status Pages') }}</div>
    </div>
</div>

<div class="section-body">

    <div class="row">
        <div class="col-12">
            @include('common.demo')
            @include('common.user')
            @include('common.errors')
            <div class="card">
                <div class="card-header">
                    <h4 class="inline-block">{{ __('List of Status Pages') }}</h4>
                    <a href="{{ route('status_page.create') }}"
                        class="btn btn-icon btn-custom float-right inline-block"><i
                            class="far fa-edit"></i>{{ __('Add Status Page') }}</a>
                </div>
                <div class="card-body">

                    @if (!count($statusPages))
                    <div class="card-body">
                        <div class="empty-state" data-height="400">
                            <div class="empty-state-icon bg-danger">
                                <i class="fas fa-question"></i>
                            </div>
                            <h2>{{ __('No data found') }} !!</h2>
                            <p class="lead">
                                {{ __('Sorry we cant find any data, to get rid of this message, make at least 1 entry') }}.
                            </p>
                            <a href="{{ route('status_page.create') }}"
                                class="btn btn-custom mt-4">{{ __('Create new one') }}</a>
                        </div>
                    </div>

                    @else
                    <div class="table-responsive">
                        <table class="table table-striped" id="table-1">
                            <thead>
                                <tr class="text-center text-capitalize">
                                    <th>{{ __('Name') }}</th>
                                    <th>{{ __('View') }}</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($statusPages as $page)
                                <tr>
                                    <td class="text-capitalize">{{ __($page->name) }}</td>

                                    @if ($enableSubdomain && $page->sub_domain)
                                    <td class="text-center"><a href="{{ "https://$page->sub_domain" }}" data-toggle="tooltip" target="blank"
                                            class="btn bg-transparent">
                                            <i class="fas fa-eye text-primary"></i></a></td>
                                    @else
                                    <td class="text-center"><a href="{{ route('showStatusPage', [$page->slug]) }}" data-toggle="tooltip"
                                        class="btn bg-transparent">
                                        <i class="fas fa-eye text-primary"></i></a></td>
                                    @endif

                                    <td class="justify-content-center form-inline">
                                        <a href="{{ route('status_page.edit', [$page->uuid]) }}"
                                            class="btn btn-sm bg-transparent"><i class="far fa-edit text-primary"
                                                aria-hidden="true" title="{{ __('Edit') }}"></i></a>

                                        @if (config('app.env') != 'demo')
                                        <form action="{{ route('status_page.destroy', [$page->uuid]) }}" method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm bg-transparent"
                                                onclick="return confirm('Are you sure?')">
                                                <i class="fa fa-trash text-danger" aria-hidden="true"
                                                    title="{{ __('Delete') }}"></i>
                                            </button>
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <br>
                        {{ $statusPages->appends($request->all())->links("pagination::bootstrap-4") }}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
@endsection