routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/lang/{locale}', function ($locale) {
    session()->put('locale', $locale);

    return redirect()->back();
});

Auth::routes(['verify' => true]);
Route::get('/admin/login', [App\Http\Controllers\Auth\LoginController::class, 'showAdminLoginForm']);
Route::post('/admin/login', [App\Http\Controllers\Auth\LoginController::class, 'adminLogin']);

Route::middleware('auth:admin')->group(function () {
    Route::get('/admin', [App\Http\Controllers\Admin\DashboardController::class, 'index']);
});

Route::get('logout', [App\Http\Controllers\Auth\LoginController::class, 'logout']);
Route::get('/', [App\Http\Controllers\User\DashboardController::class, 'index'])->name('home');

Route::resource('home', App\Http\Controllers\HomeController::class);
Route::get('/home/{plan_id}/{id}', [App\Http\Controllers\HomeController::class, 'showCurrencyWise'])->name('showCurrencyWise');

Route::resource('dashboard', App\Http\Controllers\User\DashboardController::class);
Route::resource('server_monitor', App\Http\Controllers\User\MonitorServerController::class);
Route::resource('dns_server_monitor', App\Http\Controllers\DnsMonitoringController::class);
Route::resource('keyword_monitor', App\Http\Controllers\KeywordMonitoringController::class);
Route::resource('webpage_monitor', App\Http\Controllers\User\MonitorWebpageController::class);
Route::resource('api_monitor', App\Http\Controllers\User\MonitorApiController::class);
Route::resource('website_monitor', App\Http\Controllers\User\MonitorWebsiteController::class);
Route::resource('available_plans', App\Http\Controllers\User\AddPlanController::class);
Route::resource('server_incident', App\Http\Controllers\User\ServerIncidentController::class);
Route::resource('webpage_incident', App\Http\Controllers\User\WebpageIncidentController::class);
Route::resource('website_incident', App\Http\Controllers\User\WebsiteIncidentController::class);
Route::resource('status_page', App\Http\Controllers\User\StatusPageController::class);
Route::resource('api_incident', App\Http\Controllers\User\ApiIncidentController::class);
Route::resource('ssl_monitor', App\Http\Controllers\User\SslMonitorController::class);
Route::resource('domain_monitor', App\Http\Controllers\User\DomainMonitorController::class);

Route::resource('alert_manager', App\Http\Controllers\User\AlertManagerController::class);

Route::get('/server_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorServerController::class, 'bulk_create'])->name('server_bulk_create');
Route::post('/server_monitor/bulk_create', [App\Http\Controllers\User\MonitorServerController::class, 'bulk_store'])->name('server_bulk_store');
Route::get('/webpage_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorWebpageController::class, 'bulk_create'])->name('webpage_bulk_create');
Route::post('/webpage_monitor/bulk_create', [App\Http\Controllers\User\MonitorWebpageController::class, 'bulk_store'])->name('webpage_bulk_store');
Route::get('/api_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorApiController::class, 'bulk_create'])->name('api_bulk_create');
Route::post('/api_monitor/bulk_create', [App\Http\Controllers\User\MonitorApiController::class, 'bulk_store'])->name('api_bulk_store');
Route::get('/website_monitor/bulk_create/add', [App\Http\Controllers\User\MonitorWebsiteController::class, 'bulk_create'])->name('website_bulk_create');
Route::post('/website_monitor/bulk_create', [App\Http\Controllers\User\MonitorWebsiteController::class, 'bulk_store'])->name('website_bulk_store');
Route::get('/ssl_monitor/bulk_create/add', [App\Http\Controllers\User\SslMonitorController::class, 'bulk_create'])->name('ssl_bulk_create');
Route::post('/ssl_monitor/bulk_create', [App\Http\Controllers\User\SslMonitorController::class, 'bulk_store'])->name('ssl_bulk_store');
Route::get('/domain_monitor/bulk_create/add', [App\Http\Controllers\User\DomainMonitorController::class, 'bulk_create'])->name('domain_bulk_create');
Route::post('/domain_monitor/bulk_create', [App\Http\Controllers\User\DomainMonitorController::class, 'bulk_store'])->name('domain_bulk_store');

Route::POST('/update_server_details/{uuid}', [App\Http\Controllers\User\ServerIncidentController::class, 'updateIncidentDetails'])->name('updateServerDetails');
Route::POST('/update_page_details/{uuid}', [App\Http\Controllers\User\WebpageIncidentController::class, 'updateIncidentDetails'])->name('updateWebpageDetails');
Route::POST('/update_api_details/{uuid}', [App\Http\Controllers\User\ApiIncidentController::class, 'updateIncidentDetails'])->name('updateApiDetails');
Route::delete('/delete_server_details/{uuid}', [App\Http\Controllers\User\ServerIncidentController::class, 'deleteDetails'])->name('deleteServerDetails');
Route::delete('/delete_page_details/{uuid}', [App\Http\Controllers\User\WebpageIncidentController::class, 'deleteDetails'])->name('deleteWebpageDetails');
Route::delete('/delete_api_details/{uuid}', [App\Http\Controllers\User\ApiIncidentController::class, 'deleteDetails'])->name('deleteApiDetails');

Route::post('/{id}/place_order', [App\Http\Controllers\User\AddPlanController::class, 'placeOrder'])->name('place_order');
Route::get('/profile', [App\Http\Controllers\User\ProfileController::class, 'index'])->name('userProfile');
Route::post('/profile/update', [App\Http\Controllers\User\ProfileController::class, 'update'])->name('userProfileUpdate');

Route::get('/public_page/{name}', [App\Http\Controllers\PublicPageController::class, 'monitorPublicPage'])->name('monitorPublicPage');

Route::get('status_pages/{name}', [App\Http\Controllers\ShowStatusPageController::class, 'showStatusPage'])->name('showStatusPage');

Route::resource('/admin/plans', App\Http\Controllers\Admin\PlanController::class);
Route::resource('/admin/users', App\Http\Controllers\Admin\UserController::class);
Route::resource('/admin/orders', App\Http\Controllers\Admin\OrderController::class);
Route::resource('/admin/services', App\Http\Controllers\Admin\ServiceController::class);
Route::resource('/admin/invoices', App\Http\Controllers\Admin\InvoiceController::class);
Route::resource('/admin/language', App\Http\Controllers\Admin\LanguageController::class);
Route::resource('/admin/interval', App\Http\Controllers\Admin\IntervalController::class);
Route::resource('/admin/addon', App\Http\Controllers\Admin\AddonController::class);
Route::resource('/admin/billing_address', App\Http\Controllers\Admin\AddressController::class);
Route::get('/admin/profile', [App\Http\Controllers\Admin\ProfileController::class, 'index'])->name('adminProfile');
Route::post('/admin/profile/update', [App\Http\Controllers\Admin\ProfileController::class, 'update'])->name('adminProfileUpdate');
Route::resource('/admin/gateways', App\Http\Controllers\Admin\GatewayDetailsController::class);
Route::resource('/admin/pricing', App\Http\Controllers\Admin\PricingController::class);
Route::resource('/admin/currency', App\Http\Controllers\Admin\CurrencyController::class);
Route::resource('/admin/settings', App\Http\Controllers\Admin\SettingController::class);
Route::resource('email_template', App\Http\Controllers\Admin\EmailTemplateController::class);

Route::get('/pricing/{id}/pricing_index', [App\Http\Controllers\Admin\PricingController::class, 'pricing_index'])->name('pricing_index');
Route::get('/pricing/{id}/pricing_create', [App\Http\Controllers\Admin\PricingController::class, 'pricing_create'])->name('pricing_create');
Route::get('/pricing/{plan_id}/pricing_edit/{id}', [App\Http\Controllers\Admin\PricingController::class, 'pricing_edit'])->name('pricing_edit');

Route::get('available_plans/invoice/{id}', [App\Http\Controllers\User\AddPlanController::class, 'invoice'])->name('invoice');
Route::get('/plan_details/{plan_id}/{id}', [App\Http\Controllers\User\HomeController::class, 'showCurrencyWise'])->name('showCurrencyWise');

Route::post('{id}/process_order', [App\Http\Controllers\GatewayController::class, 'processOrder'])->name('processOrder');
Route::get('success', [App\Http\Controllers\GatewayController::class, 'success'])->name('success');
Route::get('cancel', [App\Http\Controllers\GatewayController::class, 'cancel'])->name('cancel');

Route::post('{id}/stripe-payment-confirm', [App\Http\Controllers\GatewayController::class, 'stripePayment'])->name('stripe.payment');
Route::post('paypal_response', [App\Http\Controllers\GatewayController::class, 'paypalResponse'])->name('paypalResponse');

Route::post('{id}/mollie-payment', [App\Http\Controllers\GatewayController::class, 'molliePayment'])->name('mollie.payment');
Route::post('{id}/bank-transfer', [App\Http\Controllers\GatewayController::class, 'bankTransfer'])->name('bank_transfer');
Route::post('WebhookNotification', [App\Http\Controllers\GatewayController::class, 'handleMollieWebhookNotification'])->name('webhooks.mollie');

Route::get('{uuid}/refund', [App\Http\Controllers\Admin\RefundController::class, 'refund'])->name('refund');
Route::get('paypalRefund', [App\Http\Controllers\Admin\RefundController::class, 'paypalRefund'])->name('paypalRefund');

Route::post('{id}/paypal_payment', [App\Http\Controllers\GatewayController::class, 'payPalPayment'])->name('paypal.payment');
Route::get('/paypal_done', [App\Http\Controllers\GatewayController::class, 'payPalResponse'])->name('getDone');

Route::get('/get_servers_api', [App\Http\Controllers\User\StatusPageController::class, 'getServersApi'])->name('getServersApi');
Route::get('/get_webpages_api', [App\Http\Controllers\User\StatusPageController::class, 'getWebpagesApi'])->name('getWebpagesApi');

app/Models/DomainMonitor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class DomainMonitor extends Model
{
    use SoftDeletes;
    use HasFactory;

    protected $primaryKey = 'uuid';

    public $incrementing = false;

    protected $fillable = ['name', 'url', 'email', 'domain_expiry'];

    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

resources/views/domain-monitor/create.blade.php
@extends('layouts.new_theme')

@section('content')

<div class="section-header">
    <h1>{{ __('Domain Monitor') }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard.index') }}">{{ __('Dashboard') }}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('domain_monitor.index') }}">{{ __('Domain Monitor') }}</a>
        </div>
        <div class="breadcrumb-item">{{ __('Add domain') }}</div>
    </div>
</div>

<div class="section-body">
    <h2 class="section-title">{{ __('Add Domain') }}</h2>
    <p class="section-lead">{{ __('You can add a domain from here') }}.</p>

    <div class="row">
        <div class="col-12">
            @include('common.demo')
            @include('common.errors')
            <div class="card">
                <div class="card-header">
                    <h4>{{ __('Add Domain') }}</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('domain_monitor.store') }}">
                        @csrf
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Name') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                    name="name" value="{{ old('name') }}" autocomplete="name" autofocus>

                                @error('name')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror

                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                {{ __('Here you can enter a name of your choice for your domain') }}.
                                </small>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('URL') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="url" type="text" class="form-control @error('url') is-invalid @enderror"
                                    name="url" value="{{ old('url') }}" autocomplete="url" autofocus>

                                @error('url')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror

                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Here you can enter the domain name') }}. <br>
                                    Eg: {{ __('modulespanel.com') }}
                                </small>
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Email') }}:</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror"
                                    name="email" value="{{ old('email') }}" autocomplete="email" autofocus>

                                @error('email')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror

                                <small class="form-text text-muted">
                                    Eg: {{ Auth::user()->email }}
                                </small>
                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Here you can enter email id, To this email id status update emails will be sent.') }}
                                    <br>
                                    {{ __('If no email is mentioned here, mail will be sent to') }}<br />
                                    {{ Auth::user()->email }}
                                </small>
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-custom">{{ __('Add') }}</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/domain-monitor/edit.blade.php
@extends('layouts.new_theme')

@section('content')

<div class="section-header">
    <h1>{{ __('Domain Monitor') }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard.index') }}">{{ __('Dashboard') }}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('domain_monitor.index') }}">{{ __('Domain Monitor') }}</a>
        </div>
        <div class="breadcrumb-item">{{ __('Edit domain') }}</div>
    </div>
</div>

<div class="section-body">
    <h2 class="section-title">{{ __('Edit domain') }}</h2>
    <p class="section-lead">{{ __('You can update a domain from here') }}.</p>

    <div class="row">
        <div class="col-12">
            @include('common.demo')
            @include('common.errors')
            <div class="card">
                <div class="card-header">
                    <h4>{{ __('Edit domain') }}</h4>
                </div>
                <div class="card-body">
                    <form method="POST" action="{{ route('domain_monitor.update', $domain->uuid) }}">
                        @csrf
                        @method('PUT')

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Name') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                    name="name" value="{{ old('name', $domain->name) }}" autocomplete="name" autofocus>

                                @error('name')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror

                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Here you can enter a name of your choice for the domain') }}.
                                </small>
                            </div>
                        </div>
                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('URL') }}:*</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="url" type="text" class="form-control @error('url') is-invalid @enderror"
                                    name="url" value="{{ old('url', $domain->url) }}" autocomplete="url" autofocus>

                                @error('url')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror

                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Here you can enter the domain. Note that you have to enter the exact domain name, ') }}. <br>
                                    Eg: {{ __('codedeploy.io') }}
                                </small>
                            </div>
                        </div>

                        <div class="form-group row mb-4">
                            <label
                                class="col-form-label text-md-right col-12 col-md-3 col-lg-3">{{ __('Email') }}:</label>
                            <div class="col-sm-12 col-md-7">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror"
                                    name="email" value="{{ old('email', $domain->email) }}" autocomplete="email" autofocus>

                                @error('email')
                                <div class="text-danger pt-1">{{ $message }}</div>
                                @enderror

                                <small class="form-text text-muted">
                                    Eg: {{ Auth::user()->email }}
                                </small>
                                <small class="form-text text-muted"><i class="fa fa-exclamation-circle"
                                        aria-hidden="true"></i>
                                    {{ __('Here you can enter email id, To this email id status update emails will be sent.') }}
                                    <br>
                                    {{ __('If no email is mentioned here, mail will be sent to') }}<br />
                                    {{ Auth::user()->email }}
                                </small>
                            </div>
                        </div>

                        @if (config('app.env') != 'demo')
                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                            <div class="col-sm-12 col-md-7">
                                <button type="submit" class="btn btn-custom">{{ __('Update') }}</button>
                            </div>
                        </div>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/domain-monitor/index.blade.php
@extends('layouts.new_theme')

@section('content')

<div class="section-header">
    <h1>{{ __('Domain Monitor') }}</h1>
    <div class="section-header-breadcrumb">
        <div class="breadcrumb-item active"><a href="{{ route('dashboard.index') }}">{{ __('Dashboard') }}</a></div>
        <div class="breadcrumb-item"><a href="{{ route('domain_monitor.index') }}">{{ __('Domain Monitor') }}</a>
        </div>
        <div class="breadcrumb-item">{{ __('List of Domains') }}</div>
    </div>
</div>

<div class="section-body">
    <h2 class="section-title">{{ __('List of Domains') }}</h2>
    <p class="section-lead">
        {{__('Total number of domains')}}: {{ $domains->total() }}
    </p>

    <div class="row">
        <div class="col-12">
            @include('common.demo')
            @include('common.user')
            @include('common.errors')
            <div class="card">
                <div class="card-header">
                    <h4 class="d-sm-inline-block">{{ __('List of Domains') }}</h4>
                    <div class="inline-block float-sm-right mt-2 mt-sm-0">
                        <a href="{{ route('domain_monitor.create') }}" class="btn btn-icon btn-custom"><i
                                class="far fa-edit"></i>{{ __('Add Domain') }}</a>
                        <a href="{{ route('domain_bulk_create') }}" class="btn btn-icon btn-custom mr-1"><i
                                class="far fa-edit"></i>{{ __('Bulk Add') }}</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="search-bar">
                        <form action="/domain_monitor" method="get">
                            <div class="input-group mb-2">
                                <input type="text" id="search" name="search" class="form-control search-bar-input"
                                    value="{{ request()->input('search') }}" placeholder="Search">
                                <div class="input-group-btn">
                                    <button class="btn btn-custom search-bar-button"><i
                                            class="fas fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>

                    @if (!count($domains))
                    <div class="card-body">
                        <div class="empty-state" data-height="400">
                            <div class="empty-state-icon bg-danger">
                                <i class="fas fa-question"></i>
                            </div>
                            <h2>{{ __('No domain added yet under') }} !!</h2>
                            <p class="lead">
                                {{ __('Sorry we cant find any data, to get rid of this message, make at least 1 entry') }}.
                            </p>
                            <a href="{{ route('domain_monitor.create') }}"
                                class="btn btn-custom mt-4">{{ __('Create new One') }}</a>
                        </div>
                    </div>

                    @else
                    <div class="table-responsive">
                        <table class="table table-striped" id="table-1">
                            <thead>
                                <tr class="text-center text-capitalize">
                                    <th>{{ __('Name') }}</th>
                                    <th>
                                        {{ __('Domain') }}
                                    </th>
                                    <th>
                                        {{ __('Domain status') }}
                                    </th>
                                    <th>
                                        {{ __('Domain expiry date') }}
                                    </th>
                                    <th>
                                        {{ __('Last checked') }}
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($domains as $domain)
                                <tr class="text-left">
                                    <td>{{ $domain->name }}</td>
                                    <td>{{ $domain->url }}</td>
                                    <td>
                                        @if($domain->domain_expiry && $domain->domain_expiry >= $current_date)
                                        <span class="text-success">{{ __('Active') }}</span>
                                        @elseif($domain->domain_expiry && $domain->domain_expiry < $current_date)
                                        <span class="text-danger">{{ __('Expired') }}</span>
                                        @else
                                        {{ __('NA') }}
                                        @endif
                                    </td>
                                    <td>
                                        @if($domain_expiry_remaining[$domain->uuid] &&
                                        $domain_expiry_remaining[$domain->uuid] <= 7) <span class="text-danger">
                                            {{ __((1+$domain_expiry_remaining[$domain->uuid])." days left") }}</span>
                                            @else
                                            {{ $domain->domain_expiry ? \Illuminate\Support\Carbon::parse($domain->domain_expiry)->format('d-M-Y') : "NA" }}
                                            @endif
                                    </td>

                                    <td>{{$domain->updated_at->diffForHumans()}}</td>
                                    <td class="justify-content-center form-inline">
                                        <a href="{{ route('domain_monitor.edit', [$domain->uuid]) }}"
                                            class="btn btn-sm bg-transparent"><i class="far fa-edit text-primary"
                                                aria-hidden="true" title="{{ __('Edit') }}"></i></a>

                                        @if (config('app.env') != 'demo')
                                        <form action="{{ route('domain_monitor.destroy', [$domain->uuid]) }}"
                                            method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm bg-transparent"
                                                onclick="return confirm('Are you sure?')">
                                                <i class="fa fa-trash text-danger" aria-hidden="true"
                                                    title="{{ __('Delete') }}"></i>
                                            </button>
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <br>
                        {{ $domains->appends($request->all())->links("pagination::bootstrap-4") }}
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection